In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [3]:
AMD = pd.read_csv("https://query1.finance.yahoo.com/v7/finance/download/AMD?period1=1565630394&period2=1597252794&interval=1d&events=history")

AMD

,Date,Open,High,Low,Close,Adj Close,Volume
0,2019-08-12,34.160000,34.650002,32.080002,32.430000,32.430000,106737000
1,2019-08-13,32.360001,33.139999,31.719999,32.110001,32.110001,102009700
2,2019-08-14,31.000000,31.049999,29.510000,30.240000,30.240000,127521500
3,2019-08-15,30.629999,30.730000,29.209999,29.670000,29.670000,71674400
4,2019-08-16,30.309999,31.480000,30.209999,31.180000,31.180000,70469800
...,...,...,...,...,...,...,...
249,2020-08-06,85.489998,86.980003,84.779999,86.709999,86.709999,53961700
250,2020-08-07,86.669998,87.290001,82.669998,84.849998,84.849998,66498000
251,2020-08-10,85.050003,85.160004,79.320000,82.239998,82.239998,70536100
252,2020-08-11,80.709999,80.709999,76.099998,76.879997,76.879997,77762500
253,2020-08-12,78.430000,82.430000,77.559998,82.275002,82.275002,59078564

In [4]:
AMD.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2019-08-12,34.160000,34.650002,32.080002,32.430000,32.430000,106737000
1,2019-08-13,32.360001,33.139999,31.719999,32.110001,32.110001,102009700
2,2019-08-14,31.000000,31.049999,29.510000,30.240000,30.240000,127521500
3,2019-08-15,30.629999,30.730000,29.209999,29.670000,29.670000,71674400
4,2019-08-16,30.309999,31.480000,30.209999,31.180000,31.180000,70469800

In [5]:
AMD.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
249,2020-08-06,85.489998,86.980003,84.779999,86.709999,86.709999,53961700
250,2020-08-07,86.669998,87.290001,82.669998,84.849998,84.849998,66498000
251,2020-08-10,85.050003,85.160004,79.320000,82.239998,82.239998,70536100
252,2020-08-11,80.709999,80.709999,76.099998,76.879997,76.879997,77762500
253,2020-08-12,78.430000,82.430000,77.559998,82.275002,82.275002,59078564

In [6]:
AMD.describe()

,Open,High,Low,Close,Adj Close,Volume
count,254.000000,254.000000,254.000000,254.000000,254.000000,2.540000e+02
mean,46.139803,47.125158,45.158898,46.214941,46.214941,6.346635e+07
std,12.090929,12.433159,11.728844,12.180260,12.180260,2.551385e+07
min,28.280001,28.639999,27.430000,28.230000,28.230000,1.760990e+07
25%,36.452500,37.025002,36.007500,36.295001,36.295001,4.453148e+07
50%,47.844999,48.695002,46.645000,47.565000,47.565000,5.724735e+07
75%,53.402500,54.737502,52.330002,53.530001,53.530001,7.871158e+07
max,86.669998,87.290001,84.779999,86.709999,86.709999,2.053145e+08

In [7]:
import sqlite3

In [8]:
conn = sqlite3.connect("AMD.db")
c = conn.cursor()

In [9]:
conn = sqlite3.connect("AMD.db")
c = conn.cursor()

In [12]:
AMD.to_sql("AMD", conn, if_exists='replace')

In [13]:
#See data
c.execute("""SELECT * FROM AMD""")
rows = c.fetchall()
rows

[(0, '2019-08-12', 34.16, 34.650002, 32.080002, 32.43, 32.43, 106737000),
 (1,
  '2019-08-13',
  32.360001000000004,
  33.139998999999996,
  31.719998999999998,
  32.110001000000004,
  32.110001000000004,
  102009700),
 (2, '2019-08-14', 31.0, 31.049999, 29.51, 30.24, 30.24, 127521500),
 (3,
  '2019-08-15',
  30.629998999999998,
  30.73,
  29.209999,
  29.67,
  29.67,
  71674400),
 (4,
  '2019-08-16',
  30.309998999999998,
  31.48,
  30.209999,
  31.18,
  31.18,
  70469800),
 (5, '2019-08-19', 32.0, 32.189999, 31.42, 31.48, 31.48, 67596900),
 (6,
  '2019-08-20',
  30.940001000000002,
  31.309998999999998,
  30.450001,
  30.719998999999998,
  30.719998999999998,
  47924000),
 (7, '2019-08-21', 31.049999, 31.74, 30.84, 31.700001, 31.700001, 41441500),
 (8, '2019-08-22', 31.76, 31.92, 30.98, 31.9, 31.9, 47667900),
 (9, '2019-08-23', 31.299999, 31.83, 29.4, 29.540001, 29.540001, 83681100),
 (10,
  '2019-08-26',
  30.34,
  30.719998999999998,
  29.940001000000002,
  30.280001000000002,
  30.280001000000002,
  50612500),
 (11, '2019-08-27', 30.6, 30.889999, 29.6, 30.200001, 30.200001, 53229200),
 (12,
  '2019-08-28',
  29.92,
  31.18,
  29.700001,
  30.780001000000002,
  30.780001000000002,
  55835900),
 (13,
  '2019-08-29',
  31.469998999999998,
  31.83,
  31.33,
  31.450001,
  31.450001,
  44422800),
 (14,
  '2019-08-30',
  31.6,
  31.870001000000002,
  31.129998999999998,
  31.450001,
  31.450001,
  40307000),
 (15, '2019-09-03', 30.83, 31.139999, 30.68, 30.9, 30.9, 38029300),
 (16, '2019-09-04', 31.32, 31.83, 30.85, 30.950001, 30.950001, 46614600),
 (17,
  '2019-09-05',
  31.790001,
  32.049999,
  31.120001000000002,
  31.5,
  31.5,
  57861200),
 (18,
  '2019-09-06',
  31.5,
  31.51,
  30.48,
  30.559998999999998,
  30.559998999999998,
  51673000),
 (19, '2019-09-09', 30.93, 31.18, 30.24, 30.5, 30.5, 54413200),
 (20,
  '2019-09-10',
  30.219998999999998,
  30.379998999999998,
  29.77,
  30.23,
  30.23,
  48604800),
 (21, '2019-09-11', 30.379998999999998, 30.43, 29.51, 29.76, 29.76, 50631700),
 (22, '2019-09-12', 30.08, 30.84, 29.950001, 30.209999, 30.209999, 53618300),
 (23,
  '2019-09-13',
  30.27,
  30.85,
  29.950001,
  30.690001000000002,
  30.690001000000002,
  47758800),
 (24, '2019-09-16', 30.370001000000002, 31.15, 30.26, 30.83, 30.83, 52248500),
 (25, '2019-09-17', 31.07, 31.32, 30.74, 30.99, 30.99, 35011700),
 (26,
  '2019-09-18',
  30.75,
  30.889999,
  29.879998999999998,
  30.42,
  30.42,
  47027500),
 (27,
  '2019-09-19',
  30.57,
  30.959999,
  30.139999,
  30.290001,
  30.290001,
  41603000),
 (28,
  '2019-09-20',
  30.360001,
  30.469998999999998,
  29.65,
  30.049999,
  30.049999,
  79957400),
 (29,
  '2019-09-23',
  30.120001000000002,
  30.799999,
  30.07,
  30.639999,
  30.639999,
  44366800),
 (30, '2019-09-24', 30.540001, 30.75, 29.290001, 29.52, 29.52, 72963000),
 (31, '2019-09-25', 29.48, 29.65, 28.549999, 29.540001, 29.540001, 58234800),
 (32,
  '2019-09-26',
  29.67,
  29.77,
  29.0,
  29.469998999999998,
  29.469998999999998,
  40745400),
 (33,
  '2019-09-27',
  29.17,
  29.77,
  28.35,
  28.719998999999998,
  28.719998999999998,
  54091100),
 (34, '2019-09-30', 28.889999, 29.049999, 28.360001, 28.99, 28.99, 37295600),
 (35, '2019-10-01', 29.049999, 29.540001, 28.639999, 28.76, 28.76, 37081800),
 (36,
  '2019-10-02',
  28.5,
  28.85,
  28.030001000000002,
  28.309998999999998,
  28.309998999999998,
  43640700),
 (37,
  '2019-10-03',
  28.280001000000002,
  28.780001000000002,
  27.43,
  28.68,
  28.68,
  56325200),
 (38,
  '2019-10-04',
  28.83,
  29.059998999999998,
  28.280001000000002,
  29.01,
  29.01,
  34446700),
 (39, '2019-10-07', 28.9, 29.629998999999998, 28.84, 28.93, 28.93, 39337200),
 (40, '2019-10-08', 28.549999, 28.639999, 27.92, 28.23, 28.23, 44265700),
 (41,
  '2019-10-09',
  28.799999,
  28.950001,
  28.35,
  28.459999,
  28.459999,
  35661500),
 (42,
  '2019-10-10',
  28.52,
  28.889999,
  28.0,
  28.379998999999998,
  28.379998999999998,
  40660100),
 (43,
  '2019-10-11',
  28.83,
  30.200001,
  28.809998999999998,
  29.75,
  29.75,
  66256900),
 (44,
  '2019-10-14',
  29.709999,
  30.610001,
  29.379998999999998,
  30.530001000000002,
  30.530001000000002,
  44473700),
 (45,
  '2019-10-15',
  30.700001,
  30.92,
  30.17,
  30.719998999999998,
  30.719998999999998,
  41600700),
 (46,
  '2019-10-16',
  30.6,
  31.41,
  30.530001000000002,
  30.809998999999998,
  30.809998999999998,
  42804400),
 (47,
  '2019-10-17',
  31.299999,
  31.4,
  30.860001,
  31.139999,
  31.139999,
  36884400),
 (48,
  '2019-10-18',
  31.059998999999998,
  31.33,
  30.290001,
  30.969998999999998,
  30.969998999999998,
  39681700),
 (49,
  '2019-10-21',
  31.5,
  32.259997999999996,
  31.41,
  32.029999,
  32.029999,
  52182800),
 (50, '2019-10-22', 32.060001, 32.150002, 31.5, 31.51, 31.51, 36185200),
 (51, '2019-10-23', 31.09, 31.65, 30.83, 31.360001, 31.360001, 26582200),
 (52,
  '2019-10-24',
  31.58,
  31.860001,
  31.34,
  31.719998999999998,
  31.719998999999998,
  27808000),
 (53,
  '2019-10-25',
  31.9,
  32.860001000000004,
  31.83,
  32.709998999999996,
  32.709998999999996,
  45368800),
 (54, '2019-10-28', 33.16, 33.91, 33.150002, 33.689999, 33.689999, 51223600),
 (55,
  '2019-10-29',
  33.73,
  33.900002,
  32.700001,
  33.029999,
  33.029999,
  78700100),
 (56, '2019-10-30', 32.93, 33.34, 32.029999, 33.130001, 33.130001, 78228800),
 (57, '2019-10-31', 32.98, 34.34, 32.82, 33.93, 33.93, 67881600),
 (58,
  '2019-11-01',
  34.369999,
  35.0,
  34.099998,
  34.889998999999996,
  34.889998999999996,
  64238600),
 (59,
  '2019-11-04',
  35.189999,
  36.450001,
  34.759997999999996,
  36.290001000000004,
  36.290001000000004,
  83343800),
 (60, '2019-11-05', 36.560001, 37.18, 35.98, 36.150002, 36.150002, 84848600),
 (61, '2019-11-06', 36.060001, 36.48, 35.52, 35.93, 35.93, 51675100),
 (62,
  '2019-11-07',
  36.52,
  36.990002000000004,
  36.029999,
  36.279999,
  36.279999,
  54350200),
 (63,
  '2019-11-08',
  36.060001,
  36.580002,
  36.0,
  36.290001000000004,
  36.290001000000004,
  39353900),
 (64,
  '2019-11-11',
  35.959998999999996,
  36.66,
  35.580002,
  36.310001,
  36.310001,
  43511100),
 (65,
  '2019-11-12',
  36.43,
  37.130001,
  36.400002,
  36.709998999999996,
  36.709998999999996,
  58664500),
 (66,
  '2019-11-13',
  36.650002,
  37.959998999999996,
  36.580002,
  37.52,
  37.52,
  67648300),
 (67,
  '2019-11-14',
  37.509997999999996,
  38.5,
  37.360001000000004,
  38.349998,
  38.349998,
  65829500),
 (68,
  '2019-11-15',
  38.939999,
  39.369999,
  38.34,
  38.560001,
  38.560001,
  62958500),
 (69,
  '2019-11-18',
  38.650002,
  39.990002000000004,
  38.599998,
  39.880001,
  39.880001,
  66102800),
 (70,
  '2019-11-19',
  40.139998999999996,
  41.790001000000004,
  39.689999,
  41.290001000000004,
  41.290001000000004,
  94373000),
 (71, '2019-11-20', 40.959998999999996, 41.75, 40.07, 40.98, 40.98, 79767900),
 (72,
  '2019-11-21',
  40.419998,
  40.709998999999996,
  38.639998999999996,
  39.52,
  39.52,
  88069400),
 (73,
  '2019-11-22',
  39.360001000000004,
  39.889998999999996,
  38.189999,
  39.150002,
  39.150002,
  56931900),
 (74,
  '2019-11-25',
  39.5,
  40.169998,
  39.490002000000004,
  39.790001000000004,
  39.790001000000004,
  45769500),
 (75,
  '2019-11-26',
  39.299999,
  39.48,
  38.810001,
  38.990002000000004,
  38.990002000000004,
  43603300),
 (76,
  '2019-11-27',
  39.459998999999996,
  39.759997999999996,
  39.07,
  39.41,
  39.41,
  33630100),
 (77, '2019-11-29', 39.099998, 39.52, 39.02, 39.150002, 39.150002, 17609900),
 (78, '2019-12-02', 39.32, 39.41, 38.439999, 38.73, 38.73, 35710200),
 (79, '2019-12-03', 37.34, 38.93, 37.150002, 38.900002, 38.900002, 51556400),
 (80,
  '2019-12-04',
  39.380001,
  39.82,
  39.130001,
  39.689999,
  39.689999,
  44299400),
 (81,
  '2019-12-05',
  39.950001,
  40.220001,
  39.549999,
  39.619999,
  39.619999,
  35574000),
 (82,
  '2019-12-06',
  40.099998,
  40.189999,
  39.560001,
  39.630001,
  39.630001,
  31101400),
 (83, '2019-12-09', 39.459998999999996, 39.84, 38.91, 38.93, 38.93, 27928100),
 (84, '2019-12-10', 39.200001, 39.73, 38.82, 39.439999, 39.439999, 33733600),
 (85,
  '2019-12-11',
  39.439999,
  39.610001000000004,
  39.040001000000004,
  39.470001,
  39.470001,
  31698300),
 (86, '2019-12-12', 39.400002, 42.619999, 39.25, 42.59, 42.59, 86878000),
 (87,
  '2019-12-13',
  42.349998,
  42.950001,
  41.060001,
  41.150002,
  41.150002,
  79927800),
 (88, '2019-12-16', 41.73, 42.98, 41.73, 42.349998, 42.349998, 58824900),
 (89,
  '2019-12-17',
  42.509997999999996,
  43.110001000000004,
  42.150002,
  42.77,
  42.77,
  44852000),
 (90,
  '2019-12-18',
  42.790001000000004,
  43.060001,
  42.240002000000004,
  42.299999,
  42.299999,
  39083300),
 (91,
  '2019-12-19',
  42.630001,
  43.34,
  42.599998,
  42.830002,
  42.830002,
  45883000),
 (92,
  '2019-12-20',
  43.439999,
  44.259997999999996,
  43.259997999999996,
  44.150002,
  44.150002,
  68104700),
 (93,
  '2019-12-23',
  44.580002,
  45.630001,
  44.389998999999996,
  45.459998999999996,
  45.459998999999996,
  55886500),
 (94,
  '2019-12-24',
  46.099998,
  46.610001000000004,
  45.77,
  46.540001000000004,
  46.540001000000004,
  44432200),
 (95,
  '2019-12-26',
  46.990002000000004,
  47.310001,
  45.66,
  46.630001,
  46.630001,
  57562800),
 (96, '2019-12-27', 46.849998, 46.880001, 45.98, 46.18, 46.18, 36581300),
 (97,
  '2019-12-30',
  46.139998999999996,
  46.169998,
  44.66,
  45.52,
  45.52,
  41149700),
 (98,
  '2019-12-31',
  45.07,
  46.09,
  44.919998,
  45.860001000000004,
  45.860001000000004,
  31673200),
 (99,
  '2020-01-02',
  46.860001000000004,
  49.25,
  46.630001,
  49.099998,
  49.099998,
  80331100),
 (100,
  '2020-01-03',
  48.029999,
  49.389998999999996,
  47.540001000000004,
  48.599998,
  48.599998,
  73127400),
 (101,
  '2020-01-06',
  48.02,
  48.860001000000004,
  47.860001000000004,
  48.389998999999996,
  48.389998999999996,
  47934900),
 (102,
  '2020-01-07',
  49.349998,
  49.389998999999996,
  48.040001000000004,
  48.25,
  48.25,
  58061400),
 (103,
  '2020-01-08',
  47.849998,
  48.299999,
  47.139998999999996,
  47.830002,
  47.830002,
  53767000),
 (104,
  '2020-01-09',
  48.939999,
  49.959998999999996,
  48.389998999999996,
  48.970001,
  48.970001,
  76512800),
 (105,
  '2020-01-10',
  49.259997999999996,
  49.290001000000004,
  48.0,
  48.169998,
  48.169998,
  44133700),
 (106,
  '2020-01-13',
  48.66,
  48.860001000000004,
  48.240002000000004,
  48.75,
  48.75,
  34266800),
 (107,
  '2020-01-14',
  48.639998999999996,
  49.040001000000004,
  47.91,
  48.209998999999996,
  48.209998999999996,
  38563200),
 (108,
  '2020-01-15',
  48.23,
  49.080002,
  48.119999,
  48.549999,
  48.549999,
  40199900),
 (109,
  '2020-01-16',
  49.169998,
  50.310001,
  48.990002000000004,
  49.77,
  49.77,
  58898900),
 (110, '2020-01-17', 50.200001, 51.049999, 49.900002, 50.93, 50.93, 57722500),
 (111,
  '2020-01-21',
  50.959998999999996,
  51.810001,
  50.700001,
  51.049999,
  51.049999,
  49095000),
 (112, '2020-01-22', 51.630001, 51.880001, 51.200001, 51.43, 51.43, 40772200),
 (113,
  '2020-01-23',
  51.34,
  51.75,
  50.740002000000004,
  51.709998999999996,
  51.709998999999996,
  40135400),
 (114,
  '2020-01-24',
  52.279999,
  52.810001,
  49.470001,
  50.349998,
  50.349998,
  80004900),
 (115,
  '2020-01-27',
  48.450001,
  49.790001000000004,
  47.900002,
  49.259997999999996,
  49.259997999999996,
  48878600),
 (116,
  '2020-01-28',
  50.029999,
  50.849998,
  49.48,
  50.529999,
  50.529999,
  62343800),
 (117,
  '2020-01-29',
  47.84,
  48.07,
  46.099998,
  47.509997999999996,
  47.509997999999996,
  112349900),
 (118,
  '2020-01-30',
  46.490002000000004,
  48.810001,
  46.130001,
  48.779999,
  48.779999,
  70460200),
 (119,
  '2020-01-31',
  48.400002,
  48.580002,
  46.790001000000004,
  47.0,
  47.0,
  60322400),
 (120, '2020-02-03', 46.400002, 48.099998, 46.23, 48.02, 48.02, 47077000),
 (121,
  '2020-02-04',
  49.209998999999996,
  49.75,
  48.610001000000004,
  49.450001,
  49.450001,
  46302100),
 (122,
  '2020-02-05',
  50.290001000000004,
  50.419998,
  49.310001,
  49.84,
  49.84,
  42737100),
 (123,
  '2020-02-06',
  48.799999,
  49.389998999999996,
  47.630001,
  49.32,
  49.32,
  48670600),
 (124,
  '2020-02-07',
  48.91,
  50.669998,
  48.639998999999996,
  49.73,
  49.73,
  53107600),
 (125,
  '2020-02-10',
  49.470001,
  52.299999,
  49.349998,
  52.259997999999996,
  52.259997999999996,
  60971700),
 (126, '2020-02-11', 53.220001, 54.48, 52.91, 53.799999, 53.799999, 74574000),
 (127,
  '2020-02-12',
  54.529999,
  54.849998,
  53.529999,
  53.889998999999996,
  53.889998999999996,
  45994900),
 (128, '2020-02-13', 53.43, 55.029999, 53.34, 54.529999, 54.529999, 51640000),
 (129,
  '2020-02-14',
  55.189999,
  55.400002,
  54.560001,
  55.310001,
  55.310001,
  52365400),
 (130,
  '2020-02-18',
  54.939999,
  58.130001,
  54.84,
  56.889998999999996,
  56.889998999999996,
  70133200),
 (131,
  '2020-02-19',
  57.990002000000004,
  59.27,
  57.509997999999996,
  58.900002,
  58.900002,
  58597300),
 (132, '2020-02-20', 58.439999, 59.02, 56.150002, 57.27, 57.27, 74203400),
 (133,
  '2020-02-21',
  56.709998999999996,
  56.799999,
  52.889998999999996,
  53.279999,
  53.279999,
  88271100),
 (134,
  '2020-02-24',
  48.18,
  50.279999,
  47.490002000000004,
  49.119999,
  49.119999,
  86624100),
 (135,
  '2020-02-25',
  51.139998999999996,
  51.240002000000004,
  47.119999,
  47.57,
  47.57,
  88699400),
 (136,
  '2020-02-26',
  47.700001,
  49.290001000000004,
  47.07,
  47.490002000000004,
  47.490002000000004,
  86378400),
 (137,
  '2020-02-27',
  45.380001,
  46.240002000000004,
  42.209998999999996,
  44.009997999999996,
  44.009997999999996,
  105957300),
 (138,
  '2020-02-28',
  41.360001000000004,
  46.150002,
  41.040001000000004,
  45.48,
  45.48,
  100667700),
 (139,
  '2020-03-02',
  47.419998,
  47.68,
  44.66,
  47.459998999999996,
  47.459998999999996,
  102324700),
 (140, '2020-03-03', 49.029999, 50.200001, 45.669998, 46.75, 46.75, 141972300),
 (141,
  '2020-03-04',
  48.25,
  50.139998999999996,
  47.209998999999996,
  50.110001000000004,
  50.110001000000004,
  93311800),
 (142,
  '2020-03-05',
  48.68,
  49.720001,
  47.509997999999996,
  48.110001000000004,
  48.110001000000004,
  98302700),
 (143,
  '2020-03-06',
  49.439999,
  49.540001000000004,
  46.740002000000004,
  48.59,
  48.59,
  124590900),
 (144,
  '2020-03-09',
  43.029999,
  46.34,
  42.509997999999996,
  43.27,
  43.27,
  80859800),
 (145,
  '2020-03-10',
  45.41,
  45.439999,
  43.099998,
  45.380001,
  45.380001,
  76228200),
 (146,
  '2020-03-11',
  44.189999,
  45.970001,
  43.799999,
  45.700001,
  45.700001,
  101601100),
 (147,
  '2020-03-12',
  42.0,
  42.5,
  39.0,
  39.009997999999996,
  39.009997999999996,
  107461500),
 (148,
  '2020-03-13',
  42.200001,
  43.91,
  39.599998,
  43.900002,
  43.900002,
  86689700),
 (149,
  '2020-03-16',
  39.080002,
  43.369999,
  38.509997999999996,
  38.709998999999996,
  38.709998999999996,
  84545900),
 (150,
  '2020-03-17',
  40.189999,
  42.880001,
  38.299999,
  41.880001,
  41.880001,
  92741900),
 (151,
  '2020-03-18',
  39.540001000000004,
  41.950001,
  36.75,
  39.119999,
  39.119999,
  106949300),
 (152, '2020-03-19', 39.560001, 41.700001, 37.689999, 39.82, 39.82, 88939000),
 (153,
  '2020-03-20',
  41.509997999999996,
  42.48,
  39.580002,
  39.610001000000004,
  39.610001000000004,
  106859500),
 (154,
  '2020-03-23',
  40.619999,
  42.32,
  38.950001,
  41.639998999999996,
  41.639998999999996,
  101704700),
 (155,
  '2020-03-24',
  44.040001000000004,
  46.810001,
  43.990002000000004,
  46.220001,
  46.220001,
  106794200),
 (156,
  '2020-03-25',
  46.790001000000004,
  47.880001,
  44.43,
  44.630001,
  44.630001,
  93760400),
 (157, '2020-03-26', 45.779999, 47.5, 45.400002, 47.5, 47.5, 73680200),
 (158, '2020-03-27', 46.32, 47.98, 45.900002, 46.580002, 46.580002, 74599200),
 (159,
  '2020-03-30',
  47.240002000000004,
  48.459998999999996,
  46.66,
  47.860001000000004,
  47.860001000000004,
  68486600),
 (160, '2020-03-31', 47.93, 48.529999, 45.16, 45.48, 45.48, 83483700),
 (161, '2020-04-01', 44.18, 46.849998, 43.16, 43.66, 43.66, 92083100),
 (162,
  '2020-04-02',
  43.400002,
  45.279999,
  43.099998,
  44.490002000000004,
  44.490002000000004,
  79024100),
 (163, '2020-04-03', 44.299999, 44.84, 41.700001, 42.59, 42.59, 79335000),
 (164, '2020-04-06', 44.299999, 47.580002, 44.060001, 47.52, 47.52, 82294000),
 (165,
  '2020-04-07',
  48.959998999999996,
  49.650002,
  46.68,
  47.560001,
  47.560001,
  102098700),
 (166,
  '2020-04-08',
  48.07,
  49.0,
  47.610001000000004,
  48.790001000000004,
  48.790001000000004,
  64930800),
 (167,
  '2020-04-09',
  49.650002,
  50.25,
  47.720001,
  48.380001,
  48.380001,
  80357400),
 (168, '2020-04-13', 48.470001, 51.07, 48.23, 50.939999, 50.939999, 64290100),
 (169,
  '2020-04-14',
  52.240002000000004,
  55.139998999999996,
  52.110001000000004,
  54.93,
  54.93,
  85306800),
 (170,
  '2020-04-15',
  53.73,
  55.57,
  53.41,
  54.990002000000004,
  54.990002000000004,
  83814000),
 (171,
  '2020-04-16',
  55.959998999999996,
  58.080002,
  55.630001,
  56.950001,
  56.950001,
  103106500),
 (172,
  '2020-04-17',
  57.349998,
  57.759997999999996,
  55.549999,
  56.599998,
  56.599998,
  76908800),
 (173,
  '2020-04-20',
  55.98,
  58.630001,
  55.849998,
  56.970001,
  56.970001,
  72367300),
 (174, '2020-04-21', 56.900002, 57.73, 51.41, 52.919998, 52.919998, 123906400),
 (175, '2020-04-22', 54.91, 56.150002, 54.34, 55.919998, 55.919998, 63164100),
 (176,
  '2020-04-23',
  56.650002,
  57.290001000000004,
  55.639998999999996,
  55.900002,
  55.900002,
  69662700),
 (177, '2020-04-24', 55.099998, 56.779999, 54.419998, 56.18, 56.18, 72854800),
 (178,
  '2020-04-27',
  57.439999,
  58.0,
  56.25,
  56.490002000000004,
  56.490002000000004,
  62568100),
 (179,
  '2020-04-28',
  57.16,
  57.349998,
  55.299999,
  55.509997999999996,
  55.509997999999996,
  80501800),
 (180,
  '2020-04-29',
  54.529999,
  54.860001000000004,
  52.740002000000004,
  53.66,
  53.66,
  110800900),
 (181,
  '2020-04-30',
  53.43,
  54.290001000000004,
  52.029999,
  52.389998999999996,
  52.389998999999996,
  65199200),
 (182, '2020-05-01', 51.07, 51.950001, 49.09, 49.880001, 49.880001, 69562700),
 (183,
  '2020-05-04',
  49.82,
  52.610001000000004,
  49.73,
  52.560001,
  52.560001,
  62590600),
 (184,
  '2020-05-05',
  53.43,
  53.509997999999996,
  51.290001000000004,
  52.189999,
  52.189999,
  56560500),
 (185, '2020-05-06', 52.419998, 53.310001, 51.880001, 52.16, 52.16, 48138100),
 (186,
  '2020-05-07',
  52.93,
  52.970001,
  51.619999,
  51.950001,
  51.950001,
  48956600),
 (187,
  '2020-05-08',
  52.150002,
  53.27,
  51.810001,
  53.189999,
  53.189999,
  40774200),
 (188,
  '2020-05-11',
  52.900002,
  55.889998999999996,
  52.75,
  55.740002000000004,
  55.740002000000004,
  68746400),
 (189,
  '2020-05-12',
  56.209998999999996,
  56.580002,
  53.75,
  53.759997999999996,
  53.759997999999996,
  55631100),
 (190,
  '2020-05-13',
  54.040001000000004,
  55.220001,
  51.299999,
  52.18,
  52.18,
  76824700),
 (191,
  '2020-05-14',
  52.099998,
  54.540001000000004,
  51.610001000000004,
  54.509997999999996,
  54.509997999999996,
  73814000),
 (192,
  '2020-05-15',
  53.32,
  54.439999,
  52.860001000000004,
  54.200001,
  54.200001,
  66950900),
 (193, '2020-05-18', 54.98, 55.25, 54.240002000000004, 54.59, 54.59, 48679100),
 (194,
  '2020-05-19',
  54.389998999999996,
  56.73,
  54.360001000000004,
  55.470001,
  55.470001,
  60388500),
 (195,
  '2020-05-20',
  56.549999,
  56.98,
  55.630001,
  56.389998999999996,
  56.389998999999996,
  50888200),
 (196,
  '2020-05-21',
  56.68,
  56.720001,
  54.610001000000004,
  54.650002,
  54.650002,
  48496100),
 (197,
  '2020-05-22',
  54.77,
  55.369999,
  53.779999,
  55.169998,
  55.169998,
  43524100),
 (198,
  '2020-05-26',
  56.009997999999996,

In [ ]:
T.to_excel("T.xls")

pd.read_excel("T.xls")