In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/benvictoria17/Finance/main/dataset/Hospital%20Admissions%20Data/HDHI%20Admission%20data.csv")
data

,SNO,MRD No.,D.O.A,D.O.D,AGE,GENDER,RURAL,TYPE OF ADMISSION-EMERGENCY/OPD,month year,DURATION OF STAY,...,CONGENITAL,UTI,NEURO CARDIOGENIC SYNCOPE,ORTHOSTATIC,INFECTIVE ENDOCARDITIS,DVT,CARDIOGENIC SHOCK,SHOCK,PULMONARY EMBOLISM,CHEST INFECTION
0,1,234735,4/1/2017,4/3/2017,81,M,R,E,Apr-17,3,...,0,0,0,0,0,0,0,0,0,0
1,2,234696,4/1/2017,4/5/2017,65,M,R,E,Apr-17,5,...,0,0,0,0,0,0,0,0,0,0
2,3,234882,4/1/2017,4/3/2017,53,M,U,E,Apr-17,3,...,0,0,0,0,0,0,0,0,0,0
3,4,234635,4/1/2017,4/8/2017,67,F,U,E,Apr-17,8,...,0,0,0,0,0,0,0,0,0,0
4,5,234486,4/1/2017,4/23/2017,60,F,U,E,Apr-17,23,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15752,15753,699585,31/03/2019,04/04/2019,86,F,U,O,Mar-19,5,...,0,0,0,0,0,0,0,0,0,0
15753,15754,699500,3/31/2019,4/1/2019,50,M,R,E,Mar-19,2,...,0,0,0,0,0,0,0,0,0,0
15754,15755,700415,31/03/2019,09/04/2019,82,M,U,E,Mar-19,10,...,0,0,0,0,0,0,0,0,0,0
15755,15756,699524,31/03/2019,03/04/2019,59,F,U,O,Mar-19,4,...,0,0,0,0,0,0,0,0,0,0
15756,15757,699524,31/03/2019,03/04/2019,59,F,U,O,Mar-19,4,...,0,0,0,0,0,0,0,0,0,0

In [3]:
data.head

<bound method NDFrame.head of          SNO MRD No.       D.O.A       D.O.D  AGE GENDER RURAL  \
0          1  234735    4/1/2017    4/3/2017   81      M     R
1          2  234696    4/1/2017    4/5/2017   65      M     R
2          3  234882    4/1/2017    4/3/2017   53      M     U
3          4  234635    4/1/2017    4/8/2017   67      F     U
4          5  234486    4/1/2017   4/23/2017   60      F     U
...      ...     ...         ...         ...  ...    ...   ...
15752  15753  699585  31/03/2019  04/04/2019   86      F     U
15753  15754  699500   3/31/2019    4/1/2019   50      M     R
15754  15755  700415  31/03/2019  09/04/2019   82      M     U
15755  15756  699524  31/03/2019  03/04/2019   59      F     U
15756  15757  699524  31/03/2019  03/04/2019   59      F     U

      TYPE OF ADMISSION-EMERGENCY/OPD month year  DURATION OF STAY  ...  \
0                                   E     Apr-17                 3  ...
1                                   E     Apr-17                 5  ...
2                                   E     Apr-17                 3  ...
3                                   E     Apr-17                 8  ...
4                                   E     Apr-17                23  ...
...                               ...        ...               ...  ...
15752                               O     Mar-19                 5  ...
15753                               E     Mar-19                 2  ...
15754                               E     Mar-19                10  ...
15755                               O     Mar-19                 4  ...
15756                               O     Mar-19                 4  ...

       CONGENITAL UTI  NEURO CARDIOGENIC SYNCOPE  ORTHOSTATIC  \
0               0   0                          0            0
1               0   0                          0            0
2               0   0                          0            0
3               0   0                          0            0
4               0   0                          0            0
...           ...  ..                        ...          ...
15752           0   0                          0            0
15753           0   0                          0            0
15754           0   0                          0            0
15755           0   0                          0            0
15756           0   0                          0            0

       INFECTIVE ENDOCARDITIS  DVT  CARDIOGENIC SHOCK  SHOCK  \
0                           0    0                  0      0
1                           0    0                  0      0
2                           0    0                  0      0
3                           0    0                  0      0
4                           0    0                  0      0
...                       ...  ...                ...    ...
15752                       0    0                  0      0
15753                       0    0                  0      0
15754                       0    0                  0      0
15755                       0    0                  0      0
15756                       0    0                  0      0

       PULMONARY EMBOLISM CHEST INFECTION
0                       0               0
1                       0               0
2                       0               0
3                       0               0
4                       0               0
...                   ...             ...
15752                   0               0
15753                   0               0
15754                   0               0
15755                   0               0
15756                   0               0

[15757 rows x 56 columns]>

In [4]:
data.isnull().sum()

SNO                                   0
MRD No.                               0
D.O.A                                 0
D.O.D                                 0
AGE                                   0
GENDER                                0
RURAL                                 0
TYPE OF ADMISSION-EMERGENCY/OPD       0
month year                            0
DURATION OF STAY                      0
duration of intensive unit stay       0
OUTCOME                               0
SMOKING                               0
ALCOHOL                               0
DM                                    0
HTN                                   0
CAD                                   0
PRIOR CMP                             0
CKD                                   0
HB                                  252
TLC                                 286
PLATELETS                           285
GLUCOSE                             863
UREA                                241
CREATININE                          247
BNP                                8441
RAISED CARDIAC ENZYMES                0
EF                                 1505
SEVERE ANAEMIA                        0
ANAEMIA                               0
STABLE ANGINA                         0
ACS                                   0
STEMI                                 0
ATYPICAL CHEST PAIN                   0
HEART FAILURE                         0
HFREF                                 0
HFNEF                                 0
VALVULAR                              0
CHB                                   0
SSS                                   0
AKI                                   0
CVA INFRACT                           0
CVA BLEED                             0
AF                                    0
VT                                    0
PSVT                                  0
CONGENITAL                            0
UTI                                   0
NEURO CARDIOGENIC SYNCOPE             0
ORTHOSTATIC                           0
INFECTIVE ENDOCARDITIS                0
DVT                                   0
CARDIOGENIC SHOCK                     0
SHOCK                                 0
PULMONARY EMBOLISM                    0
CHEST INFECTION                       0
dtype: int64

In [5]:
data.shape

(15757, 56)

In [6]:
data.CKD.dtype

dtype('int64')

In [7]:
data.CKD = data.CKD.fillna(0)
data.HB.dtypes

dtype('O')

In [8]:
data.HB = data.HB.fillna(0)
data.TLC.dtypes

dtype('O')

In [9]:
data.TLC = data.TLC.fillna(0)
data.PLATELETS.dtypes

dtype('O')

In [10]:
data.PLATELETS = data.PLATELETS.fillna(0)
data.GLUCOSE.dtypes

dtype('O')

In [11]:
data.GLUCOSE = data.GLUCOSE.fillna(0)
data.UREA.dtypes

dtype('O')

In [12]:
data.UREA = data.UREA.fillna(0)
data.CREATININE.dtypes

dtype('O')